### ISSUE TITLE
Always return error message when we cd to a non-exist directory

### ISSUE THREAD

**Issue by zearoby** [GreyBoyka/paramiko-sshclient-session#1]
![image](https://user-images.githubusercontent.com/22544491/97518524-4d8f5e00-19d2-11eb-9a0b-c4a35d2ffdbc.png)
This screenshot shows that when we cd to a non-exist directory, and we cd to other exist directory and always return error message. Due to this issue, I must log in again to cd to a exist directory. Do you have a good idea to solve this issue?

**Comment by GreyBoyka** [comment]
fixed. on commit 73c48a1

**Comment by zearoby** [comment]
Hi GreyBoyka,

I think your code still have some issue. And we would never get stderr message from screenshot after used sdterr.read() function.
![image](https://user-images.githubusercontent.com/22544491/98613038-75ff4c80-2330-11eb-818a-56a0eba609f9.png)

So I did some changes according to your updated code. Do you think this update is fine?
![image](https://user-images.githubusercontent.com/22544491/98612800-e063bd00-232f-11eb-9e1d-0ffea66a1113.png)

Thanks
